cabal-version: 1.12

name:           paper
version:        0.1.0
description:    Please see the README on GitHub at <https://github.com/githubuser/paper#readme>
homepage:       https://github.com/kaizhang/paper#readme
bug-reports:    https://github.com/kaizhang/paper/issues
author:         Kai Zhang
maintainer:     kai@kzhang.org
copyright:      2023 Kai Zhang
license:        BSD3
license-file:   LICENSE
build-type:     Simple
extra-source-files:
    README.md
    ChangeLog.md
data-files:
    data/*.tex
    data/*.dotx
    data/*.html
    data/*.csl
    data/template/*.md
    data/template/*.yaml
    data/template/*.pdf

source-repository head
  type: git
  location: https://github.com/kaizhang/paper

library
  ghc-options: -O2 -Wall -Wcompat -Wincomplete-record-updates
  exposed-modules:
      Text.Pandoc.Paper
      Text.Pandoc.Paper.Writers
      Text.Pandoc.Paper.Readers
      Text.Pandoc.Paper.Filters
      Text.Pandoc.Paper.Filters.Authors
      Text.Pandoc.Paper.Filters.LaTeX
      Text.Pandoc.Paper.Filters.Path
      Text.Pandoc.Paper.Filters.CrossRef
      Text.Pandoc.Paper.Filters.Citations
      Text.Pandoc.Paper.Templates
      Text.Pandoc.Paper.CSL
      Text.Pandoc.Paper.Internal
  other-modules:
      Paths_paper
  hs-source-dirs:
      src
  build-depends:
      base >=4.7 && <5
    , aeson
    , bytestring >= 0.11.0
    , bytestring-encoding
    , bibtex
    , citeproc
    , containers
    , data-default
    , directory
    , doclayout
    , exceptions
    , filepath
    , file-embed
    , http-client
    , http-client-tls
    , http-types
    , mtl
    , network-uri
    , pandoc
    , pandoc-types
    , pandoc-crossref
    , parsec
    , shelly
    , temporary
    , text
    , unordered-containers
    , vector
    , yaml
  default-language: Haskell2010

executable paper
  main-is: Main.hs
  other-modules:
      Paths_paper
  hs-source-dirs:
      app
  ghc-options: -O2 -Wall -threaded
  build-depends:
      base >=4.7 && <5
    , bytestring
    , citeproc
    , containers
    , data-default
    , directory
    , doclayout
    , doctemplates
    , file-embed
    , filepath
    , http-client
    , http-client-tls
    , http-types
    , mtl
    , network-uri
    , optparse-applicative
    , pandoc
    , pandoc-types
    , paper
    , shelly
    , temporary
    , text
  default-language: Haskell2010
